// Copies the IDL and the program client from ../client so there is one source of truth.
import fs from "node:fs";

for (const f of ["pritok.json", "pritok.ts"]) fs.copyFileSync(`../client/idl/${f}`, `src/idl/${f}`);

const client = fs
  .readFileSync("../client/src/pritok.ts", "utf8")
  .replace('from "../idl/pritok.json" with { type: "json" }', 'from "@/idl/pritok.json"')
  .replace('from "../idl/pritok"', 'from "@/idl/pritok"');
fs.writeFileSync("src/lib/pritok-client.ts", `// GENERATED by scripts/sync.mjs from client/src/pritok.ts — do not edit.\n${client}`);
console.log("synced idl and client");
